name: Reusable workflow

on:
  workflow_call:

jobs:
  call-another-reusable:
    uses: MatiasNMont/github-action-demo/blob/feature.CommitInitial/go/.github/workflows/go_pipeline.yml@feature.CommitInitial
